version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./website-configuration/Dockerfile
    environment:
      YOUR_ORCID_CLIENT_ID: ${YOUR_ORCID_CLIENT_ID}
      YOUR_ORCID_CLIENT_SECRET: ${YOUR_ORCID_CLIENT_SECRET}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "4000:5000"
    depends_on:
      - postgres_database
    volumes:
      - "./website-configuration:/app"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres_database:
    build:
      context: ./
      dockerfile: ./postgres-configuration/Dockerfile
    volumes:
      - ${POSTGRES_DATABASE_DIRECTORY}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "5432" # Publishes 5432 to other containers but NOT to host machine
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  enricher_open_tree_of_life:
    build:
      context: ./
      dockerfile: ./enrichers/enricher-open-tree-of-life/Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres_database
    tmpfs:
      - /run
      - /run/lock
      - /tmp
  enricher_dirty_pipeline:
    build:
      context: ./
      dockerfile: ./enrichers/enricher-dirty-pipeline/Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres_database
    tmpfs:
      - /run
      - /run/lock
      - /tmp
  postgres_database_backup:
    profiles:
      - backup
    build:
       # Path to the directory containing your Dockerfile and scripts
      context: ./postgres-backup-configuration
      args:
        - BACKUP_SERVER_USERNAME=${BACKUP_SERVER_USERNAME}
        - BACKUP_SERVER_NAME=${BACKUP_SERVER_NAME}
        - BACKUP_SERVER_PORT=${BACKUP_SERVER_PORT}
        - BACKUP_REMOTE_PATH=${BACKUP_REMOTE_PATH}
    depends_on:
      - postgres_database
    volumes:
      - ${POSTGRES_DATABASE_DIRECTORY}:/backup_source
    secrets:
      - source: postgres_database_backup_ssh_private_key
        target: postgres_database_backup_ssh_private_key
        mode: 0600
secrets:
  postgres_database_backup_ssh_private_key:
    file: ${BACKUP_SERVER_PRIVATE_KEY_PATH}
